apiVersion: v1
kind: Namespace
metadata:
  name: legit-zone
---
apiVersion: v1
kind: Namespace
metadata:
  name: attacker
---
apiVersion: v1
kind: Namespace
metadata:
  name: verifying-resolver
---
apiVersion: v1
kind: Namespace
metadata:
  name: victim
